---
title: "BCO6007 Lab3"
author: "MariaProkofieva"
date: "28/03/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(ggplot2)

```

# Visualization - ggplot2

## Objectives

1. understand different components of ggplot2
2. being able to generate visualizations based on given data
3. uncover insights based on visualizations


```{r }
head(faithful)

str(faithful)

ggplot(data = faithful,
        mapping = aes(x = eruptions,
                      y = waiting)) +
        geom_point()
```


OR

```{r }
ggplot() +
      geom_point(mapping = aes(x = eruptions,
                               y = waiting),
                data = faithful)
  
```

### Colour

Mapping colour


```{r }
ggplot(faithful) +
      geom_point(aes(x = eruptions,
                     y = waiting,
                colour = eruptions < 3))
```

Setting colour

```{r }
ggplot(faithful) +
      geom_point(aes(x = eruptions,
                     y = waiting),
                  colour = 'steelblue')
```

### Try a different geom

```{r }
ggplot(faithful) +
      geom_histogram(aes(x = eruptions))

ggplot(faithful,
          aes(x = eruptions, y = waiting)) +
      geom_density_2d() +
      geom_point()

```

### Use of statistics

```{r }
head(mpg)
str(mpg)

ggplot(mpg) +
      geom_bar(aes(x = class))
```

Use of scales

```{r }

ggplot(mpg) +
      geom_point(
          aes(x = displ, y = hwy, colour = class)
      )

# not with scale_colour_brewer

ggplot(mpg) +
    geom_point(
        aes(x = displ, y = hwy, colour = class)
    ) +
    scale_colour_brewer(type = 'qual')

# more scales fun

ggplot(mpg) +
    geom_point(aes(x = displ, y = hwy)) +
    scale_x_continuous(breaks = c(3, 5, 6)) +
    scale_y_continuous(trans = 'log10')
```


### Facets

```{r }
ggplot(mpg) +
    geom_point(aes(x = displ, y = hwy)) +
    facet_wrap(~ class)

# use facet_grid()
ggplot(mpg) +
    geom_point(aes(x = displ, y = hwy)) +
    facet_grid(year ~ drv)

```


### Coordinates 

```{r }
ggplot(mpg) +
geom_bar(aes(x = class)) +
coord_polar()

# Changing what is mapped to angle gives a very different plot 

ggplot(mpg) +
    geom_bar(aes(x = class)) +
    coord_polar(theta = 'y') +
    expand_limits(y = 70)
```

### Theme

```{r }

mtcars2 <- within(mtcars, {
  vs <- factor(vs, labels = c("V-shaped", "Straight"))
  am <- factor(am, labels = c("Automatic", "Manual"))
  cyl  <- factor(cyl)
  gear <- factor(gear)
})

p1 <- ggplot(mtcars2) +
  geom_point(aes(x = wt, y = mpg, colour = gear)) +
  labs(title = "Fuel economy declines as weight increases",
       subtitle = "(1973-74)",
       caption = "Data from the 1974 Motor Trend US magazine.",
       tag = "Figure 1",
       x = "Weight (1000 lbs)",
       y = "Fuel economy (mpg)",
       colour = "Gears")

p1 + theme_gray() # the default
p1 + theme_bw()
p1 + theme_linedraw()
p1 + theme_light()
p1 + theme_dark()
p1 + theme_minimal()
p1 + theme_classic()
p1 + theme_void()
```

## Animation

### gganimate package

```{r }
head(economics)
str(economics)

ggplot(economics) +
    geom_line(aes(x = date, y = unemploy))

#run from console if you do not have these packages installed
# install.packages("gganimate")
# install.packages("gifski")
library(gganimate)
library(gifski)
ggplot(economics) +
    geom_line(aes(x = date, y = unemploy)) +
    transition_reveal(along = date)


ggplot(mpg) +
    geom_bar(aes(x = factor(cyl))) +
    labs(title = 'Number of cars in
  {closest_state} by number of cylinders') +
    transition_states(states = year) +
    enter_grow() +
    exit_fade()
```

```{r }
```

```{r }
```

```{r }
```

```{r }
```

```{r }
```

```{r }
```


