---
title: "Week 2 Tutorial"
author: "Maria Prokofieva"
date: "15/01/2020"
output: html_document
---

```{r, echo = FALSE, message = FALSE, warning = FALSE, warning = FALSE}
knitr::opts_chunk$set(
  message = FALSE,
  warning = FALSE,
  error = FALSE, 
  collapse = TRUE,
  comment = "#",
  fig.height = 4,
  fig.width = 8,
  fig.align = "center",
  cache = FALSE
)
library(emo)
```

## Week 2: Basics of data viz

This week we are getting into data viz with R. We already started working with RMarkdown - which is "file format" to present your data insights and communicate them to stakeholders

A screencast of the tutorial is available [here](https://www.youtube.com/channel/UCTpTqzAm8DCANz7ifhRI-sA?disable_polymer=true):

### Things to cover:

1. Basics of RMarkdown
2. `ggplot2` library: install and start using
3. Working with basic data viz



Remember: **This is not a programming unit! We focus on data and working with data**


### What I need to learn:
- work with `RMarkdown` documents with dataviz
- install and load `ggplot2` library
- work with layers in the grammar of gpaphics in `ggplot2`
- create basics dataviz "shapes": e.g. histograms, line charts, etc. in `ggplot2`
- use colour in your data viz in `ggplot2`
- use themes in `ggplot2`
- use legends, labels and axes names
- use faceting and present multiple data insights on one data viz

### Resources
ggplot2: Elegant Graphics for Data Analysis 
https://ggplot2-book.org/ 

RMarkdown: https://rmarkdown.rstudio.com/lesson-1.html


### Using data viz in `RMarkdown`

This tutorial we are going to have a closer look at `RMarkdown` and put out data viz there

### Task

- create an RMarkdown document and select `html` as output - this tells R to create an `html document` when you knit it (you can later swap it to `Word document`)

- Look at the structure of the document and syntax used. Locate the following:

⋅⋅* meta-data section
⋅⋅* R code chuncks
⋅⋅* text





## Homework

Set up your  *free* DataCamp account and have a look at the free tutorial [Introduction to R](https://www.datacamp.com/courses/free-introduction-to-r) they offer. This provides some good insights on the data types you will commonly use in R.

